library("sqldf")
students <- read.csv(file.choose())
View(students)
sqldf("select * from students ")
sqldf("select * from students where name='Veer' ")
sqldf("select * from students where marks>80 ")
sqldf("select * from students where marks==45")
sqldf("select name from students where marks=45 ")
sqldf("select DISTINCT name from students  ")
sqldf("select * from students limit 2 ")
sqldf("select name from students where marks==(select max(marks) from students)")
sqldf("select sum(marks) from students ")
sqldf("select avg(marks) from students  ")
sqldf("select max(marks) from students ")
sqldf("select min(marks) from students ")
sqldf("select * from students order by marks desc ")
sqldf("select * from students where name like '%r' ")
sqldf("select * from students where name like 'A%' ")
sqldf("select * from students where name like '%k%'")
sqldf("select name as N, marks as M from students ")
